Launch nodes and README updates.
CabrilloRoboticsClub/cabrillo_rov_2023 pull request #17
Opened 2022-12-04 21:12 UTC by mike-matera

This is a new PR without my Ansible hacks! There are now launch configurations so that the entire laptop and ROV stack can be launched with one command.

2022-12-05 02:53 UTC, cTurtle98 requested changes
overall looks good mostly but I am concerned about creating confusion with inconsistent terminology.

we have 3 device catagories
`rov` - under the water at the competition
`deck` - on the table with the pilot at the competition
`devkit` - software development team devices

please redo the "laptop" information renamed to the category you intended

2022-12-05 02:53 UTC, cTurtle98 commented on README.md
> +```
this part needs to be implemented in ansible but this can do for now

2022-12-05 02:53 UTC, cTurtle98 commented on README.md
> +```
is laptop equivalent to `devkit` or equivalent to `deck controller` ?

our terminology defined 3 device groups:
rov - the pi on the rov
deck - the yet-to-be-built computer that acts as the remote control for the robot
devkit - the computers we are writing our code on

2022-12-05 02:53 UTC, cTurtle98 commented on README.md
> +```
we should probably add ansible to add this to the .bash_profile on devkit category devices

2022-12-05 02:53 UTC, cTurtle98 commented on README.md
> +```
this also needs to be done with ansible on devkit category devices

2022-12-05 02:53 UTC, cTurtle98 commented on README.md
> +start_x=1
we should use ansible blockinfile to do this

2022-12-05 02:53 UTC, cTurtle98 commented on launch/rov.yaml
> +
github is complaining that there is no newline at the end of the file here

2022-12-05 02:53 UTC, cTurtle98 commented on launch/laptop.yaml
> +# Launch file for the nodes on the laptop
should this be devkit or deck ? we dont have a "laptop" device type defined

2022-12-05 15:26 UTC, DerVerrater commented on README.md
> +```
This is a bit more steps. *Some* automation would be nice. It could just be a Makefile, though. This is meant to be operated directly by developers on their kit, not automatically for the full-build process.

Lmk your thoughts, though, I'm not gonna close this as aggressively as the others :v

2022-12-06 00:37 UTC, cTurtle98 approved these changes

2022-12-06 00:37 UTC, merged